### PR TITLE
Convert bugzilla URL into something which can be read and debug by humans.

### PR DESCRIPTION
**Pull request by nbp**
This patch a preliminary work such that I can make a follow-up patch to fix the "P1 affecting or may affect" search, and make sure we all agree on the substance of the changes.

I tested locally, this patch returns the same results.

### CODE REVIEW

**Comment by nbp** [comment]
Note, if you land this PR, It would be trivial to fix and review #5, #32 and #33 afterward.

**Comment by emceeaich** [comment]
Thanks. I'm traveling, so if there's someone we can nominate to review this PR, that'd be good. I'll ask Marion Daly if she can.

**Comment by MarionDaly** [comment]
Reviewed the PR, the code looks clean enough and I have no objections to it being put in but we need proper testing instructions and Emma will need to verify it doesn't break anything. 

Please include the following:
1. What issue are you trying to fix
2. What are your testing instructions (please be explicit)  (forgive me, but if we have automated testing we will need a new automated test for this as well)


Once done, Emma if you can verify this PR by testing it against a production-like instance of Bugzilla and verifying there's no regressions please merge it in.

**Comment by nbp** [comment]
Thanks for the review.

> What issue are you trying to fix

I am trying to fix the search queries (#5, #32, #33 and #38), but the current set of URL are unreadable and involve some time-consuming manual testing to verify the validity of the changes.  This change is a preliminary change such that we can avoid doing some time-consuming manual testing in the future and instead easily read the search queries within the code.

Therefore, implementing new searches or fixing the current one should no longer require round-trips with Bugzilla after this change.

> What are your testing instructions (please be explicit) (forgive me, but if we have automated testing we will need a new automated test for this as well)

If there is some automated test, I am not aware of any.

What I did for testing locally, was to check that I do get the same number of bugs and that the search queries are identical when comparing a local instance (as documented in the README) with the https://are-we-triaged-yet.herokuapp.com/ hosted version.

**Comment by emceeaich** [comment]
I appreciate what you are proposing here, but it is adding an abstraction which I'm not sold on for updating queries. For now I'd like to close the request until there's tests for this. We can use the existing query syntax for the question in #38.

**Pull request closed without merging**
